jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: ${{ secrets.SSH_KNOWN_HOSTS }}

      - name: Deploy via PM2 on Remote VM
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} '
            set -e

            # Если ещё не клонировали — клонируем через SSH
            if [ ! -d .git ]; then
              echo "🔄 Клонируем репозиторий через SSH..."
              git clone git@github.com:${{ github.repository }} . --branch main --depth 1
            else
              echo "🔄 Обновляем код..."
              git reset --hard
              git pull
            fi

            echo "📥 Устанавливаем зависимости"
            npm install -g pm2
            npm install —g verdaccio

            echo "🔄 Останавливаем PM2..."
            pm2 stop all || echo "⚠️ Нет запущенных процессов PM2"
            pm2 delete all || echo "⚠️ Нет приложений для удаления"

            pm2 start verdaccio — — listen 0.0.0.0:4001

            echo "✅ PM2 перезапущен успешно"
            pm2 list

            echo "🔄 Обновляем конфиг nginx..."
            sudo nginx -t
            sudo systemctl reload nginx

             echo "✅ Nginx перезапущен успешно"
          '
      - name: Report Success
        if: success()
        run: echo "✅ Deploy is successfull!"

      - name: Report Failure
        if: failure()
        run: echo "❌ Fail to deploy on VM!"
